package controller;

public enum Commands {
	AC_JB_CLEAN,
	AC_JB_CALCULATE,
	AC_JB_SEARCH,
	AC_CB_EARLYER,
	AC_CB_LOCAL,
	AC_CB_PUBLIC,
	AC_MI_HELP,
	AC_MI_SETTINGS,
	
	
	
	AC_SEARCH_BY_WORDS,
	C_LOG_IN,
	AC_SHOW_COURSES_BUTTON,
	AC_SHOW_TEACHERS_BUTTON,
	AC_SHOW_STUDENTS_BUTTON,
	AC_SHOW_SUBJECTS_BUTTON,
	AC_SHOW_LOGIN_BUTTON,
	AC_SHOW_LOGOUT_BUTTON,
	AC_SHOW_REGISTER_BUTTON
}
